Patch up hic_breakfinder Dockerfile so that it works without manual intervention.

diff --git a/docker/hic_breakfinder/Dockerfile b/docker/hic_breakfinder/Dockerfile
--- a/docker/hic_breakfinder/Dockerfile
+++ b/docker/hic_breakfinder/Dockerfile
@@ -7,14 +7,20 @@ ENV DEBIAN_FRONTEND noninteractive
 
 # hic_breakfinder installation is pretty fragile. 
 # It needs JasonCpp, Eigen, and bamtools installed first.  
-# Note that bamtools must be version 2.4.2.   Not 2.4.0, or 2.4.1, or 2.5.x. 
+# Note that it seems to require bamtools version 2.4.2.   Not 2.4.0, or 2.4.1, or 2.5.x. 
 # It's also very picky about setting CPPFLAGS
 # Couldn't get configure to add -lz properly, so ended up just doing the linking step manually (g++ ...)
-# This also means the make will fail generating an error, thus "make; exit 0"
+# This also means the make will fail generating an error, thus "make || echo ..."
+
 # None of this is ideal and it'd be good to figure out how to get ./configure;make to work properly
 # but this at least gives us something that works and documents the issues for whoever wants to take that on. 
 
-RUN apt-get update -y\    
+# Another approach would be to use AWK to switch out the defective link line with the correct one.  
+
+# Note, to see all the compiler output you can build like: 
+# docker build --no-cache --progress=plain -t kjdurbin/hic_breakfinder .
+
+RUN apt-get update -y \
 	&& DEBIAN_FRONTEND=noninteractive \
 	&& apt-get install -y \
     awscli \
@@ -36,21 +42,23 @@ RUN apt-get update -y\
     && cd / \
     && wget https://github.com/pezmaster31/bamtools/archive/refs/tags/v2.4.2.tar.gz \
     && tar -zxvf v2.4.2.tar.gz \
-    && cd bamtools-2.4.2 \ 
+    && cd bamtools-2.4.2 \
     && mkdir build \
     && cd build \
     && cmake .. \
     && make \
-    && make install \ 
-    && cd / \       
+    && make install 
+
+RUN cd / \
     && git clone https://github.com/dixonlab/hic_breakfinder.git \
     && cd hic_breakfinder \
     && ./configure CPPFLAGS="-I /usr/local/include/bamtools -I /usr/local/include/Eigen/" LDFLAGS="-L /usr/local/lib -lz" \
-    && make; exit 0 \
+    && make || echo "Make failed as expected.  Fear not, we'll fix it..." \
     && cd src \
-    && g++  -g -O2 -g -L /usr/local/lib -L /lib/x86_64-linux-gnu/ -o hic_breakfinder hic_breakfinder.o  -lbamtools -lz \
+    && g++ -g -O2 -g -L /usr/local/lib -L /lib/x86_64-linux-gnu/ -o hic_breakfinder hic_breakfinder.o  -lbamtools -lz \
     && cd .. \
-    && make install \	
+    && make install \
+    && cd / \
 	&& apt-get clean \
 	&& apt-get purge \
 	&& rm -rf /var/lib/apt/lists/* /tmp/*
